### ISSUE TITLE
Initial configuration error

### ISSUE THREAD

**Issue by drmaddy736** [olixr/MudPi#25]
I have installed mudpi, mudpi assistant and UI , without error. I could connect to AP(192.168.2.1). But then after clicking  'getting started' next page is not loading. Also in terminal, running mudpi.py gives error as 
mudpi.config file not found

**Comment by olixr** [comment]
V0.10.0 is in the `feature` branch. This is a big update to the system and will be suggested to update in the coming days. 

Your errors sound like you are missing a config file. You should create your own before running MudPi. An example is provided for you to start from but you still need to either rename it or make a copy. i.e. `cp mudpi.config.example mudpi.config` 

In regards to the dashboard that issue should be manged on the other repo. Its likely the error because of the updates to the core and the dashboard is still not fully updated to reflect them yet.

**Comment by drmaddy736** [comment]
Yes... initial error was due to missing config file but then I created one but very next error was no redis module then I copy pasted redis folder into mudpi/core but then next error on running mudpi.py was ;modulenotfound
error , no module named 'board'. So I think mudpi.py script is not able to
get Access to other installed modules. I did try to find folder where all modules would be there but I couldn't. By the way I am physician here India
with love for farming and little bit of tinkering with softwares.

Thank u for Replay
Namaste 🙏

**Comment by olixr** [comment]
Hey @drmaddy736 did you resolve you configuration issue?

**Comment by drmaddy736** [comment]
No not yet.

**Comment by olixr** [comment]
If you need more help please provide copies of your log files, configs and screenshots of any errors. Otherwise it can be hard to figure out the root of your issue. 

At initial notes it seems that you are missing a config file and just need to create one. 

If you need info on the config format you can read more here: https://mudpi.app/docs/configuration-basics

**Comment by drmaddy736** [comment]
Will do, thanks!

**Comment by olixr** [comment]
The v0.10.0 has been merged to the master branch. I am closing this issue as the config should be resolved with the update.
